// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Use real Supabase (DEMO_MODE disabled)
const DEMO_MODE = false;

// Environment validation - only in development
if (typeof window !== 'undefined' && import.meta.env.DEV) {
  if (!SUPABASE_URL) {
    console.warn('⚠️ VITE_SUPABASE_URL not configured');
  }
  if (!SUPABASE_PUBLISHABLE_KEY) {
    console.warn('⚠️ VITE_SUPABASE_PUBLISHABLE_KEY not configured');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: async (url, options) => {
        if (import.meta.env.DEV) {
          console.log('📡 Supabase API call:', url);
        }
        return fetch(url, options);
      }
    }
  }
);

export { DEMO_MODE };